services:
    php:
        build:
            context: docker/php
            dockerfile: Dockerfile
        command: ["tail", "-f", "/dev/null"]
        working_dir: /src
        env_file:
            - .env.docker
        volumes:
            - .:/src
    postgres:
        image: postgres:17
        ports:
            - "5432:5432"
        env_file:
            - .env.docker
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust
        volumes:
            - testdb-postgres:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U ${PG_TEST_DATABASE_USER:-postgres} -d ${PG_TEST_DATABASE_NAME:-postgres}"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 10s
    mysql:
        image: mysql:8.0-oracle
        volumes:
            - testdb-mysql:/var/lib/mysql
        ports:
            - "3306:3306"
        env_file:
            - .env.docker
        healthcheck:
            test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=\"$${MYSQL_ROOT_PASSWORD}\" --silent"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 20s
    mariadb:
        image: mariadb:12-noble
        volumes:
            - testdb-mariadb:/var/lib/mysql
        ports:
            - "3307:3306"
        env_file:
            - .env.docker
        healthcheck:
            test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
            interval: 5s
            timeout: 5s
            retries: 10
            start_period: 20s
    mail:
        image: axllent/mailpit
        ports:
            - "8025:8025"
            - "1025:1025"

volumes:
    testdb-postgres: {}
    testdb-mysql: {}
    testdb-mariadb: {}
