<?php

declare(strict_types=1);

namespace ByLexus\TaskRunner\Tests\Integration;

use ByLexus\TaskRunner\Queue\QueueConfiguration;
use ByLexus\TaskRunner\Queue\SchemaManager;
use ByLexus\TaskRunner\Tests\Support\PostgresIntegrationConnection;
use PHPUnit\Framework\TestCase;

final class SchemaManagerIntegrationTest extends TestCase
{
    public function testBootstrapCreatesSchemaIdempotently(): void {
        $pdo = PostgresIntegrationConnection::requirePdo($this);
        $tableName = PostgresIntegrationConnection::uniqueTableName();

        try {
            $configuration = new QueueConfiguration($tableName);
            $schemaManager = new SchemaManager($pdo, $configuration);

            $schemaManager->bootstrap();
            $schemaManager->bootstrap();

            self::assertTrue($schemaManager->tableExists());
            self::assertTrue($schemaManager->blobTableExists());
            self::assertTrue($this->columnExists($pdo, $tableName, 'cleanup_at'));
            self::assertTrue($this->columnExists($pdo, $tableName, 'priority'));
            self::assertTrue($this->columnExists($pdo, $configuration->getBlobTableName(), 'content'));
            self::assertTrue($this->columnAllowsNulls($pdo, $tableName, 'payload_json'));
            self::assertTrue($this->taskIdIsIdentityColumn($pdo, $tableName));
        } finally {
            PostgresIntegrationConnection::dropTableIfExists($pdo, $tableName);
        }
    }

    public function testExportedDdlCanCreateSchemaExplicitly(): void {
        $pdo = PostgresIntegrationConnection::requirePdo($this);
        $tableName = PostgresIntegrationConnection::uniqueTableName();

        try {
            $ddl = (new SchemaManager($pdo, new QueueConfiguration($tableName)))->exportDdl();

            foreach ($this->statementsFromDdl($ddl) as $statement) {
                $pdo->exec($statement);
            }

            $schemaManager = new SchemaManager($pdo, new QueueConfiguration($tableName));

            self::assertTrue($schemaManager->tableExists());
            self::assertTrue($schemaManager->blobTableExists());
            $schemaManager->validate();
            self::assertTrue($this->columnExists($pdo, $tableName, 'cleanup_at'));
            self::assertTrue($this->columnExists($pdo, $tableName, 'priority'));
            self::assertTrue($this->columnExists($pdo, sprintf('%s_blob_data', $tableName), 'content'));
            self::assertTrue($this->columnAllowsNulls($pdo, $tableName, 'payload_json'));
            self::assertTrue($this->taskIdIsIdentityColumn($pdo, $tableName));
            self::assertTrue($this->indexExists($pdo, sprintf('%s_cleanup_at_idx', $tableName)));
            self::assertTrue($this->indexExists($pdo, sprintf('%s_blob_task_id_idx', $tableName)));
        } finally {
            PostgresIntegrationConnection::dropTableIfExists($pdo, $tableName);
        }
    }

    public function testBootstrapCreatesRequiredIndexes(): void {
        $pdo = PostgresIntegrationConnection::requirePdo($this);
        $tableName = PostgresIntegrationConnection::uniqueTableName();

        try {
            $configuration = new QueueConfiguration($tableName);
            $schemaManager = new SchemaManager($pdo, $configuration);

            $schemaManager->bootstrap();

            self::assertTrue($this->indexExists($pdo, sprintf('%s_cleanup_at_idx', $tableName)));
            self::assertTrue($this->indexExists($pdo, sprintf('%s_task_status_available_at_idx', $tableName)));
            self::assertTrue($this->indexExists($pdo, sprintf('%s_blob_task_id_idx', $tableName)));
        } finally {
            PostgresIntegrationConnection::dropTableIfExists($pdo, $tableName);
        }
    }

    public function testBootstrapAddsMissingPriorityColumnToExistingQueueTable(): void {
        $pdo = PostgresIntegrationConnection::requirePdo($this);
        $tableName = PostgresIntegrationConnection::uniqueTableName();

        try {
            $pdo->exec(
                sprintf(
                    <<<'SQL'
CREATE TABLE "%s" (
    task_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_class TEXT NOT NULL,
    step_class TEXT NULL,
    task_status TEXT NOT NULL,
    task_created_at TIMESTAMPTZ NOT NULL,
    task_started_at TIMESTAMPTZ NULL,
    task_finished_at TIMESTAMPTZ NULL,
    cleanup_at TIMESTAMPTZ NULL,
    step_status TEXT NULL,
    step_attempt INTEGER NOT NULL DEFAULT 0,
    step_started_at TIMESTAMPTZ NULL,
    step_finished_at TIMESTAMPTZ NULL,
    payload_json JSONB NULL,
    result_json JSONB NULL,
    error_json JSONB NULL,
    available_at TIMESTAMPTZ NOT NULL,
    claimed_at TIMESTAMPTZ NULL,
    claimed_by TEXT NULL,
    last_error_code TEXT NULL,
    last_error_message TEXT NULL,
    cancel_requested BOOLEAN NOT NULL DEFAULT FALSE,
    cancel_reason TEXT NULL,
    updated_at TIMESTAMPTZ NOT NULL
)
SQL,
                    $tableName,
                ),
            );

            $schemaManager = new SchemaManager($pdo, new QueueConfiguration($tableName));
            $schemaManager->bootstrap();

            self::assertTrue($this->columnExists($pdo, $tableName, 'priority'));
        } finally {
            PostgresIntegrationConnection::dropTableIfExists($pdo, $tableName);
        }
    }

    public function testBootstrapCreatesConfiguredSchemaAndTablesInsideIt(): void {
        $pdo = PostgresIntegrationConnection::requirePdo($this);
        $tableName = PostgresIntegrationConnection::uniqueTableName();
        $schemaName = PostgresIntegrationConnection::uniqueSchemaName();

        try {
            $configuration = new QueueConfiguration($tableName, $schemaName);
            $schemaManager = new SchemaManager($pdo, $configuration);

            $schemaManager->bootstrap();

            self::assertTrue($schemaManager->tableExists());
            self::assertTrue($schemaManager->blobTableExists());
            self::assertTrue($this->columnExists($pdo, $tableName, 'cleanup_at', $schemaName));
            self::assertTrue($this->columnExists($pdo, $configuration->getBlobTableName(), 'content', $schemaName));
            self::assertTrue($this->indexExists($pdo, sprintf('%s_cleanup_at_idx', $tableName), $schemaName));
        } finally {
            PostgresIntegrationConnection::dropSchemaIfExists($pdo, $schemaName);
        }
    }

    private function columnExists(\PDO $pdo, string $tableName, string $columnName, ?string $schemaName = null): bool {
        $statement = $pdo->prepare(
            sprintf(
                'SELECT EXISTS (
                    SELECT 1
                    FROM information_schema.columns
                    WHERE table_schema = %s
                      AND table_name = :table_name
                      AND column_name = :column_name
                )',
                $schemaName === null ? 'current_schema()' : ':schema_name',
            ),
        );
        $statement->execute($this->schemaParameters($schemaName, [
            'table_name' => $tableName,
            'column_name' => $columnName,
        ]));

        return (bool) $statement->fetchColumn();
    }

    private function taskIdIsIdentityColumn(\PDO $pdo, string $tableName, ?string $schemaName = null): bool {
        $statement = $pdo->prepare(sprintf(
            'SELECT is_identity, identity_generation
                FROM information_schema.columns
                WHERE table_schema = %s
                  AND table_name = :table_name
                  AND column_name = :column_name',
            $schemaName === null ? 'current_schema()' : ':schema_name',
        ));
        $statement->execute($this->schemaParameters($schemaName, [
            'table_name' => $tableName,
            'column_name' => 'task_id',
        ]));

        $row = $statement->fetch(\PDO::FETCH_ASSOC);

        if (!is_array($row)) {
            return false;
        }

        return $row['is_identity'] === 'YES' && $row['identity_generation'] === 'BY DEFAULT';
    }

    private function columnAllowsNulls(
        \PDO $pdo,
        string $tableName,
        string $columnName,
        ?string $schemaName = null,
    ): bool {
        $statement = $pdo->prepare(sprintf(
            'SELECT is_nullable
                FROM information_schema.columns
                WHERE table_schema = %s
                  AND table_name = :table_name
                  AND column_name = :column_name',
            $schemaName === null ? 'current_schema()' : ':schema_name',
        ));
        $statement->execute($this->schemaParameters($schemaName, [
            'table_name' => $tableName,
            'column_name' => $columnName,
        ]));

        return $statement->fetchColumn() === 'YES';
    }

    private function indexExists(\PDO $pdo, string $indexName, ?string $schemaName = null): bool {
        $statement = $pdo->prepare(sprintf(
            'SELECT EXISTS (
                SELECT 1
                FROM pg_indexes
                WHERE schemaname = %s
                  AND indexname = :index_name
            )',
            $schemaName === null ? 'current_schema()' : ':schema_name',
        ));
        $statement->execute($this->schemaParameters($schemaName, ['index_name' => $indexName]));

        return (bool) $statement->fetchColumn();
    }

    /** @param array<string, scalar|null> $parameters
     * @return array<string, scalar|null>
     */
    private function schemaParameters(?string $schemaName, array $parameters): array {
        if ($schemaName === null) {
            return $parameters;
        }

        $parameters['schema_name'] = $schemaName;

        return $parameters;
    }

    /** @return list<string> */
    private function statementsFromDdl(string $ddl): array {
        $normalizedDdl = rtrim($ddl);

        if (str_ends_with($normalizedDdl, ';')) {
            $normalizedDdl = substr($normalizedDdl, 0, -1);
        }

        return array_values(
            array_filter(
                array_map('trim', explode(";\n\n", $normalizedDdl)),
                static fn (string $statement): bool => $statement !== '',
            ),
        );
    }
}
